### ISSUE TITLE
Vehicle Support

### ISSUE THREAD

**Issue by feedbackex** [AFCStudio/BCRYExporter#103]
__BCRY Exporter Vehicle Exporting Support__

- [x] **Parent/Child relation exporting** support for vehicle; child objects have to be same node as parent. #105
- [x] New ___write_child_objects__ function. #106
- [x] __Dummy__ object exporting. #107
- [x] __Dummy__ object UDP adding. #114
- [x] New __hull__ UDP property. #112
- [x] New [document ](http://bcry.afcstudio.org/documents/vehicle-setup/) for vehicle setup at official site.
